version: '3'
services:
  # 服務的名字
  app:
    # 該路徑底下需要包含Dockerfile
    build: ./
    # 對應哪個port
    ports:
      - "8082:5002"
    environment:
    - DB_HOST=db
    - DB_NAME=blog_db
    - DB_USER=blogapp
    - DB_PASSWORD=KBaM534TMpUWTEFU
    depends_on:
    - db
  db:
    # db 映像檔名稱
    image: postgres
    # docker deamon開啟時該container就會重啟
    restart: always
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=blogapp
      - POSTGRES_PASSWORD=KBaM534TMpUWTEFU
      - POSTGRES_DB=blog_db
