version: '3'
services:
  # 服務的名字
  app:
    # 該路徑底下需要包含Dockerfile
    build: ./
    restart: always
    # 對應哪個port
    ports:
      - "8082:5002"
      # 資料庫的 user 密碼
    environment:
    - DB_HOST=db
    - DB_NAME=blog_db
    - DB_USER=blogapp
    - DB_PASSWORD=uDb2ezDsbKsxsZk8
    depends_on:
    - db
  db:
    # db 映像檔名稱
    image: postgres
    # docker deamon開啟時該container就會重啟
    restart: always
    ports: 
      - "5432:5432"
    # 創建映像檔的密碼也就是資料庫密碼  
    environment:
      - POSTGRES_USER=blogapp
      - POSTGRES_PASSWORD=nz93N9fupzWetEXG
      - POSTGRES_DB=blog_db
