version: '3'
services:
  # 服務的名字
  app:
    # 該路徑底下需要包含Dockerfile
    build: .
    # image 名稱
    image: blog_image
    # 名稱
    container_name: blog_container
    # 對應哪個port
    ports:
      - "8000:8000"
    environment:
    - DB_HOST=db
    - DB_NAME=blog_db
    - DB_USER=blogapp
    - DB_PASSWORD=KBaM534TMpUWTEFU
    depends_on:
    - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=blogapp
      - POSTGRES_PASSWORD=KBaM534TMpUWTEFU
      - POSTGRES_DB=blog_db
